### ISSUE TITLE
Add Ombi support

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/web-to-plex#16]
It would be nice to be able to add a movie or TV show to Ombi if it doesn't exist on Plex.

(suggested via Facebook)

**Comment by SuperPotatoMen** [comment]
Thanks! cool (https://github.com/tidusjar/PlexRequests.Net)

**Comment by SpaceK33z** [comment]
Note that this is going to take a while, since I don't use Plex Requests at the moment. If anybody wants to do a PR that would be very welcome (but discuss first please).

**Comment by aglasson** [comment]
I’m confused as to what supporting Ombi (Plex request) would achieve, what benefits would come from it. 

All Ombi does is add a request to the likes of Sonarr, Radarr, etc. which is what this does already.

It would just add a bit more unnecessary complexity IMHO.

**Comment by Ephellon** [comment]
Read about Ombi--the only real reason(s) to add Ombi support would be for 1) the user base (6M+) and/or simplicity... the user could setup just Ombi and have a single API request from there. 2) Ombi also supports more than just Plex, so that could lead to a larger support base (but would no longer be "Web to Plex," rather "Web to [Media Server]").

**Comment by Ephellon** [comment]
OMDBI's only documentation is within the application, I'll install it when I get some time and work on this.

**Comment by Ephellon** [comment]
Done. I'm adding another feature, pushing commit in an hour or two.

The Ombi feature has the added benefit of logging into Plex (share tokens), and acting as a media manager (similar to sonarr/radarr)
