### ISSUE TITLE
Add support for Watcher? (CouchPotato alternative)

### ISSUE THREAD

**Issue by Flippage** [SpaceK33z/web-to-plex#24]
Hey, so there's a new alternative to CouchPotato called Watcher. I'm keen to try it out because it's apparently a lot better than couchpotato already.

The only thing stopping me is that I love this Movieo extension you've built, and I don't want to lose access to it.

Any chance you could integrate Watcher support into this? It has an API.

https://github.com/nosmokingbandit/watcher

**Comment by SpaceK33z** [comment]
Hmm, it doesn't seem to support torrents so I'm not likely going to use it myself.

At this moment it's not really easy to add support for Watcher with a PR, because there is no support for multiple services yet. In the options there should be a nice tab menu which lists the services (Couchpotato, Sonarr, Watcher, etc.).There are more tickets (#14, #16) with feature requests for other services, so after building support for that it's easier to fix this issue.

**Comment by MartinAyla** [comment]
I have installed watcher and I really like it (I have already uninstalled Couchpotato - finally!).

I already miss the integration with your great extension, so I really hope you will add watcher support at some point :)

**Comment by estrellagus** [comment]
I always would love this option.  Watcher (Or Radarr ) seems extremely promising and already better than couchpotato it seem

**Comment by SpaceK33z** [comment]
Hey, I have implemented support for Radarr now. It was a lot of work, and in my opinion there is nothing better than Radarr so I won't be adding support for Watcher, sorry.

**Comment by Ephellon** [comment]
Sorry to necro-chat, but Watcher support has been added in an upcoming release.
